name = "RustFFT"
uuid = "b7f167ac-9de6-40dd-9818-ec636999de39"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
version = "0.1.0"

[deps]
JlrsCore = "29be08bc-e5fd-4da2-bbc1-72011c6ea2c9"
rustfft_jll = "54eccfce-c43a-54d5-bb22-f204d2e1c97b"

[compat]
julia = "1.6"
JlrsCore = "0.1"
rustfft_jll = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
