name = "RustFFT"
uuid = "b7f167ac-9de6-40dd-9818-ec636999de39"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
version = "0.3.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
JlrsCore = "29be08bc-e5fd-4da2-bbc1-72011c6ea2c9"
rustfft_jll = "54eccfce-c43a-54d5-bb22-f204d2e1c97b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AbstractFFTs = "1"
JlrsCore = "0.5"
julia = "1.6"
rustfft_jll = "0.4"
Reexport = "0.2, 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
